# Generated by Django 5.2.15 on 2026-07-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('todo', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('priority', models.CharField(choices=[('H', 'بالا'), ('M', 'متوسط'), ('L', 'پایین')], default='M', max_length=1)),
                ('status', models.CharField(choices=[('DO', 'انجام شده'), ('DN', 'در حال انجام'), ('SE', 'دیده شده ')], default='SE', max_length=2)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
