# Generated by Django 5.2.15 on 2026-07-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo',
            new_name='body',
        ),
        migrations.AddField(
            model_name='todo',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=1),
            preserve_default=False,
        ),
    ]
