# Generated by Django 5.2.15 on 2026-07-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('NE', '-------'), ('DO', 'انجام شده'), ('DN', 'در حال انجام'), ('SE', 'دیده شده ')], default='NE', max_length=2),
        ),
    ]
