# Generated by Django 5.2.15 on 2026-07-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ سررسید'),
        ),
    ]
